// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type AutoTopOffEvent interface {
	IsAutoTopOffEvent()
}

type AutoWaterChangeEvent interface {
	IsAutoWaterChangeEvent()
}

type ATOJobComplete struct {
	Timestamp int     `json:"timestamp"`
	Duration  float64 `json:"duration"`
	Volume    float64 `json:"volume"`
}

func (ATOJobComplete) IsAutoTopOffEvent() {}

type ATOJobError struct {
	Timestamp int    `json:"timestamp"`
	Error     string `json:"error"`
}

func (ATOJobError) IsAutoTopOffEvent() {}

type AWCJobError struct {
	Timestamp int    `json:"timestamp"`
	Error     string `json:"error"`
}

func (AWCJobError) IsAutoWaterChangeEvent() {}

type AWCStatus struct {
	Timestamp   int     `json:"timestamp"`
	Duration    float64 `json:"duration"`
	FreshVolume float64 `json:"fresh_volume"`
	WasteVolume float64 `json:"waste_volume"`
}

func (AWCStatus) IsAutoWaterChangeEvent() {}

type DoserComponentInput struct {
	PumpID   string  `json:"pump_id"`
	DoseRate float64 `json:"dose_rate"`
}

type DoserInput struct {
	Components []*DoserComponentInput `json:"components"`
}

type MaxFillVolumeError struct {
	Timestamp int `json:"timestamp"`
}

func (MaxFillVolumeError) IsAutoTopOffEvent() {}

type UncontrolledPumpError struct {
	Timestamp int    `json:"timestamp"`
	PumpID    string `json:"pump_id"`
	Error     string `json:"error"`
}

func (UncontrolledPumpError) IsAutoTopOffEvent()      {}
func (UncontrolledPumpError) IsAutoWaterChangeEvent() {}

type WaterLevelAlert struct {
	Timestamp int `json:"timestamp"`
}

func (WaterLevelAlert) IsAutoTopOffEvent() {}

type SensorKind string

const (
	SensorKindHigh  SensorKind = "HIGH"
	SensorKindAlert SensorKind = "ALERT"
)

var AllSensorKind = []SensorKind{
	SensorKindHigh,
	SensorKindAlert,
}

func (e SensorKind) IsValid() bool {
	switch e {
	case SensorKindHigh, SensorKindAlert:
		return true
	}
	return false
}

func (e SensorKind) String() string {
	return string(e)
}

func (e *SensorKind) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SensorKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SensorKind", str)
	}
	return nil
}

func (e SensorKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
