// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AtoEvents                    string
	AutoTopOffs                  string
	AutoTopOffsWaterLevelSensors string
	AutoWaterChanges             string
	AwcEvents                    string
	Calibrations                 string
	DoserComponents              string
	Dosers                       string
	Doses                        string
	Firmatas                     string
	GorpMigrations               string
	Pumps                        string
	WaterLevelSensors            string
}{
	AtoEvents:                    "ato_events",
	AutoTopOffs:                  "auto_top_offs",
	AutoTopOffsWaterLevelSensors: "auto_top_offs_water_level_sensors",
	AutoWaterChanges:             "auto_water_changes",
	AwcEvents:                    "awc_events",
	Calibrations:                 "calibrations",
	DoserComponents:              "doser_components",
	Dosers:                       "dosers",
	Doses:                        "doses",
	Firmatas:                     "firmatas",
	GorpMigrations:               "gorp_migrations",
	Pumps:                        "pumps",
	WaterLevelSensors:            "water_level_sensors",
}
